apiVersion: v1
kind: Secret
metadata:
  name: kubernetes-demo-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  url: https://github.com/n2Electrons/kubernetes-demo.git
  type: git